# Generated by Django 2.2 on 2019-04-23 20:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_auto_20190423_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='takedown_time',
            field=models.TimeField(default=datetime.time(16, 18, 27, 275801)),
        ),
    ]
